import MilSolutions
-- C02
import MilSolutions.C02_Basics.S01_Calculating
import MilSolutions.C02_Basics.S02_Proving_Identities_in_Algebraic_Structures
import MilSolutions.C02_Basics.S03_Using_Theorems_and_Lemmas
import MilSolutions.C02_Basics.S04_More_on_Order_and_Divisibility
import MilSolutions.C02_Basics.S05_Proving_Facts_about_Algebraic_Structures
-- C03
import MilSolutions.C03_Logic.S01_Implication_and_the_Universal_Quantifier
import MilSolutions.C03_Logic.S02_The_Existential_Quantifier
import MilSolutions.C03_Logic.S03_Negation
import MilSolutions.C03_Logic.S04_Conjunction_and_Iff
import MilSolutions.C03_Logic.S05_Disjunction
import MilSolutions.C03_Logic.S06_Sequences_and_Convergence
-- C04
import MilSolutions.C04_Sets_and_Functions.S01_Sets
import MilSolutions.C04_Sets_and_Functions.S02_Functions
import MilSolutions.C04_Sets_and_Functions.S03_The_Schroeder_Bernstein_Theorem
-- C05
import MilSolutions.C05_Elementary_Number_Theory.S01_Irrational_Roots
import MilSolutions.C05_Elementary_Number_Theory.S02_Induction_and_Recursion
import MilSolutions.C05_Elementary_Number_Theory.S03_Infinitely_Many_Primes
-- C06
import MilSolutions.C06_Structures.S01_Structures
import MilSolutions.C06_Structures.S02_Algebraic_Structures
import MilSolutions.C06_Structures.S03_Building_the_Gaussian_Integers
-- C07
import MilSolutions.C07_Hierarchies.S01_Basics
import MilSolutions.C07_Hierarchies.S02_Morphisms
import MilSolutions.C07_Hierarchies.S03_Subobjects

def main : IO Unit :=
  IO.println s!"Hello, {hello}!"
