import MilSolutions
-- C02
import MilSolutions.C02_Basics.S01_Calculating
import MilSolutions.C02_Basics.S02_Proving_Identities_in_Algebraic_Structures
import MilSolutions.C02_Basics.S03_Using_Theorems_and_Lemmas
import MilSolutions.C02_Basics.S04_More_on_Order_and_Divisibility
import MilSolutions.C02_Basics.S05_Proving_Facts_about_Algebraic_Structures
-- C03
import MilSolutions.C03_Logic.S01_Implication_and_the_Universal_Quantifier
import MilSolutions.C03_Logic.S02_The_Existential_Quantifier
import MilSolutions.C03_Logic.S03_Negation
import MilSolutions.C03_Logic.S04_Conjunction_and_Iff
import MilSolutions.C03_Logic.S05_Disjunction
import MilSolutions.C03_Logic.S06_Sequences_and_Convergence
-- C04
import MilSolutions.C04_Sets_and_Functions.S01_Sets
import MilSolutions.C04_Sets_and_Functions.S02_Functions
import MilSolutions.C04_Sets_and_Functions.S03_The_Schroeder_Bernstein_Theorem

def main : IO Unit :=
  IO.println s!"Hello, {hello}!"
